[workspace]
members = [
  "crates/lib",
  "crates/proof-pipeline",
  "crates/tree-builder",
  "crates/sequencer",
  "crates/proof-submitter",
  "crates/tests"
]
resolver = "2"

[workspace.dependencies]
# Async runtime
tokio = { version = "1.40", features = ["full", "macros", "rt-multi-thread"] }

# Database
sqlx = { version = "0.8.5", features = ["postgres", "runtime-tokio-rustls", "macros", "migrate", "uuid", "chrono", "json"] }

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.133"

# Error handling
thiserror = "1.0"
anyhow = "1.0.95"

# Logging and tracing
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter", "json"] }
log = "0.4"
env_logger = "0.11"

# Web framework
axum = "0.8.3"
tower = { version = "0.4.13", features = ["full", "util"] }
tower-http = { version = "0.4", features = ["trace", "cors"] }
hyper = "0.14.27"

# Starknet interaction
starknet = "0.13.0"
starknet-crypto = "0.7.4"

# Ethereum interaction
ethers = { version = "2.0.14", features = ["rustls", "ws"] }

# HTTP client
reqwest = { version = "0.12.15", features = ["json", "multipart"] }

# Environment and utility
dotenv = "0.15"
uuid = { version = "1.8", features = ["v4", "serde"] }
chrono = { version = "0.4.38", features = ["serde"] }
sha2 = "0.10"
sha3 = "0.10.8"
url = "2.5.4"
hex = "0.4"
rand = "0.8"
config = "0.15.11"
clap = { version = "4.0", features = ["derive"] }
toml = "0.8.23"

# Alloy ecosystem
alloy = "0.14.0"
alloy-json-rpc = "0.15.6"
alloy-primitives = "1.0.0"
alloy-rpc-client = "0.15.6"
alloy-transport-http = "0.15.6"
alloy-sol-types = "1.0.0"

# Testing & mocking
mockall = "0.13.1"
tokio-test = "0.4"
pretty_assertions = "1.4.0"
mockito = "0.31"
tempfile = "3.20.0"

# Futures and async utils
futures = "0.3"
futures-util = "0.3.31"
async-trait = "0.1.88"

# Misc
structopt = "0.3"
num-bigint = "0.4"
num-traits = "0.2"
